const express = require('express');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const { protect } = require('../middleware/auth');
const User = require('../models/User');

const router = express.Router();

// Initialize Gemini API
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || 'dummy_key');

// @route   POST /api/games/start
// @desc    Start a game session
// @access  Private
router.post('/start', protect, async (req, res) => {
    try {
        const { gameType, userId } = req.body;

        // You could add logic here to track game starts, validate user, etc.
        // For now, we just acknowledge the start.

        res.json({
            success: true,
            message: `Started ${gameType} game`,
            data: {
                gameType,
                startTime: new Date()
            }
        });
    } catch (error) {
        console.error('Start game error:', error);
        res.status(500).json({
            success: false,
            message: 'Server error'
        });
    }
});

// @route   POST /api/games/trivia
// @desc    Get 10 trivia questions from AI (or fallback)
// @access  Private
router.post('/trivia', protect, async (req, res) => {
    const fallbackQuestions = [
        {
            question: "Which gas is most abundant in the Earth's atmosphere?",
            options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
            correctAnswer: 1,
            explanation: "Nitrogen makes up about 78% of Earth's atmosphere."
        },
        {
            question: "What is the primary cause of global warming?",
            options: ["Deforestation", "Greenhouse Gases", "Ozone Layer Depletion", "Volcanic Eruptions"],
            correctAnswer: 1,
            explanation: "Greenhouse gases trap heat in the atmosphere, causing the planet to warm."
        },
        {
            question: "Which renewable energy source relies on the moon's gravitational pull?",
            options: ["Solar Power", "Wind Power", "Tidal Power", "Geothermal Energy"],
            correctAnswer: 2,
            explanation: "Tidal power is generated by the gravitational forces of the moon and sun."
        },
        {
            question: "What is the process by which plants convert sunlight into energy?",
            options: ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"],
            correctAnswer: 1,
            explanation: "Photosynthesis is the process used by plants to convert light energy into chemical energy."
        },
        {
            question: "Which of the following is NOT a fossil fuel?",
            options: ["Coal", "Natural Gas", "Uranium", "Petroleum"],
            correctAnswer: 2,
            explanation: "Uranium is a nuclear fuel, not a fossil fuel formed from ancient organic matter."
        },
        {
            question: "What is the main purpose of the ozone layer?",
            options: ["To trap heat", "To block UV radiation", "To produce oxygen", "To reflect sunlight"],
            correctAnswer: 1,
            explanation: "The ozone layer absorbs most of the Sun's ultraviolet radiation."
        },
        {
            question: "Which material takes the longest to decompose?",
            options: ["Paper", "Plastic", "Glass", "Aluminum"],
            correctAnswer: 2,
            explanation: "Glass can take up to 1 million years to decompose, though it is 100% recyclable."
        },
        {
            question: "What does the '3 R's' of waste management stand for?",
            options: ["Read, Register, Recall", "Reduce, Reuse, Recycle", "Run, Rest, Recover", "Random, Rare, Real"],
            correctAnswer: 1,
            explanation: "Reduce, Reuse, and Recycle are the three essential components of environmentally-responsible consumer behavior."
        },
        {
            question: "Which animal is often used as a symbol for conservation?",
            options: ["Lion", "Giant Panda", "Eagle", "Shark"],
            correctAnswer: 1,
            explanation: "The Giant Panda is the logo of the World Wildlife Fund (WWF) and a symbol of conservation."
        },
        {
            question: "What is the largest ocean on Earth?",
            options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
            correctAnswer: 3,
            explanation: "The Pacific Ocean is the largest and deepest of Earth's oceanic divisions."
        }
    ];

    try {
        if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_api_key_here') {
            return res.json({
                success: true,
                data: fallbackQuestions
            });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-pro" });
        const prompt = "Generate 10 multiple-choice questions about environmental sustainability, climate change, ecology, and renewable energy. Return ONLY a JSON array of objects with this format: [{ \"question\": \"string\", \"options\": [\"string\", \"string\", \"string\", \"string\"], \"correctAnswer\": number (0-3), \"explanation\": \"string\" }]";

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();

        // Clean up the response to ensure it's valid JSON
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const triviaData = JSON.parse(jsonStr);

        res.json({
            success: true,
            data: triviaData
        });
    } catch (error) {
        console.error('Trivia generation error (using fallback):', error.message);
        // Fallback to local questions on API error
        res.json({
            success: true,
            data: fallbackQuestions
        });
    }
});

// @route   GET /api/games/daily-challenge
// @desc    Get daily challenge from AI
// @access  Private
router.get('/daily-challenge', protect, async (req, res) => {
    try {
        const user = await User.findById(req.user.id);

        // Check if already completed today
        let isCompleted = false;
        if (user.lastDailyChallengeCompleted) {
            const lastCompleted = new Date(user.lastDailyChallengeCompleted);
            const today = new Date();
            if (lastCompleted.toDateString() === today.toDateString()) {
                isCompleted = true;
            }
        }

        if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_api_key_here') {
            return res.json({
                success: true,
                data: {
                    title: "Plastic-Free Day",
                    description: "Avoid using single-use plastics for the entire day. Use a reusable water bottle and bag.",
                    points: 50,
                    completed: isCompleted
                }
            });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-pro" });
        const prompt = "Generate a daily environmental challenge for a student. Return ONLY a JSON object with this format: { \"title\": \"string\", \"description\": \"string\", \"points\": number (between 20-100) }";

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();

        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const challengeData = JSON.parse(jsonStr);
        challengeData.completed = isCompleted;

        res.json({
            success: true,
            data: challengeData
        });
    } catch (error) {
        console.error('Challenge generation error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to generate challenge'
        });
    }
});

// @route   POST /api/games/complete-challenge
// @desc    Complete a challenge and earn points
// @access  Private
router.post('/complete-challenge', protect, async (req, res) => {
    try {
        const { points } = req.body;

        const user = await User.findById(req.user.id);
        if (!user) {
            return res.status(404).json({ success: false, message: 'User not found' });
        }

        // Check if already completed today
        if (user.lastDailyChallengeCompleted) {
            const lastCompleted = new Date(user.lastDailyChallengeCompleted);
            const today = new Date();
            if (lastCompleted.toDateString() === today.toDateString()) {
                return res.status(400).json({
                    success: false,
                    message: 'You have already completed the daily challenge today'
                });
            }
        }

        user.points += points;
        user.lastDailyChallengeCompleted = new Date();
        await user.save();

        res.json({
            success: true,
            message: `Challenge completed! You earned ${points} points.`,
            data: {
                points: user.points,
                completed: true
            }
        });
    } catch (error) {
        console.error('Complete challenge error:', error);
        res.status(500).json({
            success: false,
            message: 'Server error'
        });
    }
});

// @route   GET /api/games/daily-tip
// @desc    Get a daily eco tip
// @access  Private
router.get('/daily-tip', protect, async (req, res) => {
    try {
        const tips = [
            "Turn off the tap while brushing your teeth to save up to 8 gallons of water a day.",
            "Unplug electronics when not in use to prevent phantom energy loss.",
            "Use a reusable water bottle instead of buying plastic ones.",
            "Take shorter showers to conserve water and energy.",
            "Recycle paper, plastic, glass, and aluminum whenever possible.",
            "Walk, bike, or use public transportation instead of driving.",
            "Plant a tree or start a small garden to help absorb carbon dioxide.",
            "Use cloth bags for shopping instead of plastic bags.",
            "Switch to LED light bulbs to save energy and money.",
            "Compost food scraps to reduce waste and create nutrient-rich soil."
        ];

        // Simple daily rotation based on day of year
        const dayOfYear = Math.floor((new Date() - new Date(new Date().getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
        const tipIndex = dayOfYear % tips.length;

        res.json({
            success: true,
            data: {
                tip: tips[tipIndex]
            }
        });
    } catch (error) {
        console.error('Daily tip error:', error);
        res.status(500).json({
            success: false,
            message: 'Server error'
        });
    }
});

// @route   POST /api/games/adventure/start
// @desc    Start a new eco-adventure story
// @access  Private
router.post('/adventure/start', protect, async (req, res) => {
    try {
        if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_api_key_here') {
            return res.json({
                success: true,
                data: {
                    scenario: "You are the newly elected mayor of GreenValley. The city is suffering from severe air pollution due to old factories and heavy traffic. Citizens are demanding change. What is your first act?",
                    options: [
                        "Invest heavily in public transportation and bike lanes.",
                        "Impose strict regulations on factory emissions.",
                        "Launch a tree-planting campaign to create green zones.",
                        "Subsidize electric vehicles for all residents."
                    ]
                }
            });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-pro" });
        const prompt = "Start a text-based adventure game about environmental sustainability. The user is in a role (e.g., mayor, park ranger, scientist). Describe the initial situation and a problem they face. Provide 4 distinct options for their first action. Return ONLY a JSON object with this format: { \"scenario\": \"string\", \"options\": [\"string\", \"string\", \"string\", \"string\"] }";

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();

        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const gameData = JSON.parse(jsonStr);

        res.json({
            success: true,
            data: gameData
        });
    } catch (error) {
        console.error('Adventure start error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to start adventure'
        });
    }
});

// @route   POST /api/games/adventure/turn
// @desc    Process a turn in the eco-adventure
// @access  Private
router.post('/adventure/turn', protect, async (req, res) => {
    try {
        const { currentScenario, choice } = req.body;

        if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_api_key_here') {
            return res.json({
                success: true,
                data: {
                    consequence: "Your decision was well-received! Pollution levels dropped slightly, but some business owners are unhappy about the costs.",
                    nextScenario: "Now, a waste management crisis has emerged. The landfill is overflowing. What do you do?",
                    options: [
                        "Implement a mandatory recycling program.",
                        "Build a waste-to-energy plant.",
                        "Export waste to a neighboring region.",
                        "Encourage composting with subsidies."
                    ],
                    gameOver: false,
                    points: 10
                }
            });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-pro" });
        const prompt = `Continue this text adventure. 
        Previous Scenario: "${currentScenario}"
        User Choice: "${choice}"
        
        Describe the consequence of this choice (positive or negative impact on environment). 
        Then describe the next situation/problem.
        Provide 4 new options.
        Decide if the game is over (e.g., if they made too many bad choices or reached a goal).
        Award points (0-20) based on the eco-friendliness of the choice.
        
        Return ONLY a JSON object with this format: 
        { 
            "consequence": "string", 
            "nextScenario": "string", 
            "options": [\"string\", \"string\", \"string\", \"string\"], 
            "gameOver": boolean, 
            "points": number 
        }`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();

        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const turnData = JSON.parse(jsonStr);

        // Update user points if points were awarded
        if (turnData.points > 0) {
            await User.findByIdAndUpdate(req.user.id, {
                $inc: { points: turnData.points }
            });
        }

        res.json({
            success: true,
            data: turnData
        });
    } catch (error) {
        console.error('Adventure turn error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to process turn'
        });
    }
});

// @route   POST /api/games/simulation/start
// @desc    Start a new eco-city simulation
// @access  Private
router.post('/simulation/start', protect, async (req, res) => {
    try {
        const initialStats = {
            pollution: 50, // 0-100 (lower is better)
            budget: 100000, // Currency
            happiness: 70 // 0-100 (higher is better)
        };

        if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_api_key_here') {
            return res.json({
                success: true,
                data: {
                    stats: initialStats,
                    event: "A large coal power plant proposes an expansion. It will bring jobs and money but increase pollution significantly.",
                    options: [
                        { text: "Approve expansion", impact: "Budget ++, Pollution ++" },
                        { text: "Reject expansion", impact: "Happiness +, Budget -" },
                        { text: "Propose green alternative", impact: "Budget --, Pollution --, Happiness ++" }
                    ]
                }
            });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
        const prompt = `Start a city simulation game.
        Initial Stats: Pollution: 50, Budget: 100000, Happiness: 70.
        Generate an initial event related to urban management or environment.
        Provide 3 distinct options for the player.
        Return ONLY a JSON object: { "event": "string", "options": [{ "text": "string", "impact": "string" }] }`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const eventData = JSON.parse(jsonStr);

        res.json({
            success: true,
            data: {
                stats: initialStats,
                ...eventData
            }
        });
    } catch (error) {
        console.error('Simulation start error:', error);
        // Fallback
        res.json({
            success: true,
            data: {
                stats: {
                    pollution: 50,
                    budget: 100000,
                    happiness: 70
                },
                event: "A large coal power plant proposes an expansion. It will bring jobs and money but increase pollution significantly.",
                options: [
                    { text: "Approve expansion", impact: "Budget ++, Pollution ++" },
                    { text: "Reject expansion", impact: "Happiness +, Budget -" },
                    { text: "Propose green alternative", impact: "Budget --, Pollution --, Happiness ++" }
                ]
            }
        });
    }
});

// @route   POST /api/games/simulation/turn
// @desc    Process a turn in the eco-city simulation
// @access  Private
router.post('/simulation/turn', protect, async (req, res) => {
    try {
        const { currentStats, choice } = req.body;

        if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_api_key_here') {
            // Fallback logic for demo purposes if no API key
            return res.json({
                success: true,
                data: {
                    stats: {
                        pollution: currentStats.pollution + 5,
                        budget: currentStats.budget + 5000,
                        happiness: currentStats.happiness - 2
                    },
                    event: "Traffic congestion is increasing. Commuters are angry.",
                    options: [
                        { text: "Build more roads", impact: "Budget -, Pollution +" },
                        { text: "Invest in public transit", impact: "Budget --, Pollution --" },
                        { text: "Implement congestion pricing", impact: "Budget +, Happiness -" }
                    ],
                    gameOver: false
                }
            });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
        const prompt = `City Simulation Turn.
        Current Stats: Pollution: ${currentStats.pollution}, Budget: ${currentStats.budget}, Happiness: ${currentStats.happiness}.
        Player Choice: "${choice}".
        
        1. Calculate new stats based on the choice.
           - Pollution: 0-100 (Game over if > 90)
           - Budget: Can go negative (Game over if < -50000)
           - Happiness: 0-100 (Game over if < 20)
        2. Generate the NEXT event.
        3. Provide 3 options.
        4. Check for Game Over conditions.
        
        Return ONLY a JSON object: 
        { 
            "stats": { "pollution": number, "budget": number, "happiness": number },
            "event": "string", 
            "options": [{ "text": "string", "impact": "string" }],
            "gameOver": boolean,
            "gameOverReason": "string (optional)"
        }`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const turnData = JSON.parse(jsonStr);

        res.json({
            success: true,
            data: turnData
        });
    } catch (error) {
        console.error('Simulation turn error:', error);
        // Fallback
        res.json({
            success: true,
            data: {
                stats: {
                    pollution: req.body.currentStats.pollution + 5,
                    budget: req.body.currentStats.budget + 5000,
                    happiness: req.body.currentStats.happiness - 2
                },
                event: "Traffic congestion is increasing. Commuters are angry.",
                options: [
                    { text: "Build more roads", impact: "Budget -, Pollution +" },
                    { text: "Invest in public transit", impact: "Budget --, Pollution --" },
                    { text: "Implement congestion pricing", impact: "Budget +, Happiness -" }
                ],
                gameOver: false
            }
        });
    }
});

module.exports = router;
